title: Akash Soti
description: Personal website

url: "https://akashsoti.com"
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
 - title: Work
   url: /index.html
 - title: Prototypes
   url: /prototypes
 - title: About
   url: /about

social:
   github: akashsoti
   twitter: https://twitter.com/akashsoti
   facebook: https://www.facebook.com/akash.soti
   email: akashsoti@gmail.com

google_analytics: "G-S5X8XG2WVW"
